package cli

import (
	"encoding/json"
	"fmt"
	"os"
	"strconv"
	"strings"

	"github.com/spf13/cobra"
	"github.com/udit-001/waypoint/internal/db"
)

var artifactsCmd = &cobra.Command{
	Use:     "artifacts",
	Short:   "Manage AI-generated content artifacts",
	Aliases: []string{"artifact"},
	Long: `List, view, add, and delete content generated by the AI skills
(emails, cover letters, interview prep, resume analysis, career summaries).

Artifacts are created by the skills and stored with all their variants
(e.g. a cover-letter artifact holds the formal, casual, and creative versions).
You can also add them manually with the add command.

Examples:
  waypoint artifacts add --skill cover-letter --title "Cover for Google" --variant-content "Dear..."
  waypoint artifacts list
  waypoint artifacts list --skill cover-letter --job 5
  waypoint artifacts get 12
  waypoint artifacts delete 12`,
}

// --- list ---

var artifactsListFlags struct {
	skill string
	job   int64
	all   bool
}

var artifactsListCmd = &cobra.Command{
	Use:   "list",
	Short: "List artifacts",
	Long: `List generated artifacts. By default excludes archived ones.

Filter by skill type (--skill) and/or job (--job).
Use --all to include archived artifacts.

Examples:
  waypoint artifacts list
  waypoint artifacts list --skill cover-letter
  waypoint artifacts list --job 5
  waypoint artifacts list --all`,
	Args: cobra.NoArgs,
	RunE: func(cmd *cobra.Command, args []string) error {
		arts, err := store.GetArtifacts(artifactsListFlags.skill, artifactsListFlags.job, artifactsListFlags.all)
		if err != nil {
			return formatError("failed to list artifacts", err)
		}

		if jsonOut {
			if arts == nil {
				arts = []db.Artifact{}
			}
			printJSON(arts)
			return nil
		}

		fmt.Println()
		if len(arts) == 0 {
			fmt.Println("  No artifacts found.")
			fmt.Println()
			return nil
		}

		rows := make([][]string, 0, len(arts))
		for _, a := range arts {
			var variants []db.ArtifactVariant
			_ = json.Unmarshal([]byte(a.Variants), &variants)
			rows = append(rows, []string{
				strconv.FormatInt(a.ID, 10),
				a.SkillID,
				a.Title,
				strconv.Itoa(len(variants)),
				formatDateShort(a.UpdatedAt),
			})
		}

		fmt.Println(formatTable(
			[]string{"ID", "Skill", "Title", "Variants", "Updated"},
			rows,
		))
		fmt.Println()
		return nil
	},
}

// --- get ---

var artifactsGetCmd = &cobra.Command{
	Use:   "get <id>",
	Short: "Show artifact details",
	Long: `Show full details of an artifact including all variants.

Examples:
  waypoint artifacts get 12
  waypoint artifacts get 12 --json`,
	Args: cobra.ExactArgs(1),
	RunE: func(cmd *cobra.Command, args []string) error {
		id, err := strconv.ParseInt(args[0], 10, 64)
		if err != nil {
			return fmt.Errorf("invalid artifact ID: %s", args[0])
		}

		art, err := store.GetArtifact(id)
		if err != nil {
			return err
		}

		if jsonOut {
			printJSON(art)
			return nil
		}

		fmt.Println()
		fmt.Printf("  ID:       %d\n", art.ID)
		fmt.Printf("  Skill:    %s\n", art.SkillID)
		fmt.Printf("  Title:    %s\n", art.Title)
		fmt.Printf("  Archived: %v\n", art.Archived)
		fmt.Printf("  Created:  %s\n", formatDateTime(art.CreatedAt))
		fmt.Printf("  Updated:  %s\n", formatDateTime(art.UpdatedAt))

		var variants []db.ArtifactVariant
		if err := json.Unmarshal([]byte(art.Variants), &variants); err != nil {
			return fmt.Errorf("parse variants: %w", err)
		}

		fmt.Println()
		fmt.Printf("  Variants (%d):\n", len(variants))
		for _, v := range variants {
			fmt.Println()
			fmt.Printf("  ── %s ──\n", v.Label)
			fmt.Println(v.Content)
		}
		fmt.Println()
		return nil
	},
}

// --- delete ---

var artifactsDeleteFlags struct {
	force bool
}

var artifactsDeleteCmd = &cobra.Command{
	Use:   "delete <id>",
	Short: "Delete an artifact",
	Long: `Delete an artifact by ID. Prompts for confirmation
unless --force is used.

Examples:
  waypoint artifacts delete 12
  waypoint artifacts delete 12 --force`,
	Args: cobra.ExactArgs(1),
	RunE: func(cmd *cobra.Command, args []string) error {
		id, err := strconv.ParseInt(args[0], 10, 64)
		if err != nil {
			return fmt.Errorf("invalid artifact ID: %s", args[0])
		}

		art, err := store.GetArtifact(id)
		if err != nil {
			return err
		}

		if !artifactsDeleteFlags.force {
			fmt.Printf("  Delete artifact %d (%s)? [y/N]: ", id, art.Title)
			var confirm string
			fmt.Scanln(&confirm)
			if confirm != "y" && confirm != "Y" && confirm != "yes" {
				fmt.Println("  Cancelled.")
				return nil
			}
		}

		if err := store.DeleteArtifact(id); err != nil {
			return formatError("failed to delete artifact", err)
		}

		if jsonOut {
			printJSON(map[string]any{"deleted": true, "id": id, "title": art.Title})
			return nil
		}

		fmt.Println()
		fmt.Printf("  ✓ Deleted artifact %d: %s\n", id, art.Title)
		fmt.Println()
		return nil
	},
}

// --- add ---

var artifactsAddFlags struct {
	skill          string
	job            int64
	title          string
	titleFile      string
	variants       string
	variantsFile   string
	variantLabel   string
	variantContent string
	variantFile    string
	options        string
	optionsFile    string
}

var artifactsAddCmd = &cobra.Command{
	Use:   "add --skill <id> --title <title>",
	Short: "Add a new artifact",
	Long: `Add a new artifact manually.

Provide content in one of four ways:
  1. --variant-content   Inline text for a single variant
  2. --variant-file (-f) Read single-variant content from a file
  3. --variants           JSON array of [{"label":"...","content":"..."}]
  4. --variants-file      Read the JSON variants array from a file

Using --variant-file or --variants-file is recommended when content is
multiline or contains special characters — especially useful for AI agents
that write to a temp file first.

For --title, you can also use --title-file to read from a file.

Examples:
  # Inline single variant
  waypoint artifacts add --skill cover-letter --title "Cover for Google" --variant-content "Dear..."

  # Read content from a file (ideal for multiline / AI-generated text)
  waypoint artifacts add --skill cover-letter --title "Cover" -f /tmp/cover.txt
  waypoint artifacts add --skill email-generator --title "Follow-up" --job 3 -f /tmp/email.txt --variant-label Casual

  # Multiple variants from a JSON file
  waypoint artifacts add --skill cover-letter --title "Cover" --variants-file /tmp/variants.json

  # Multiple variants inline
  waypoint artifacts add --skill cover-letter --title "Cover" --variants '[{"label":"Formal","content":"Dear..."}]'`,
	Args: cobra.NoArgs,
	RunE: func(cmd *cobra.Command, args []string) error {
		var jobID *int64
		if artifactsAddFlags.job > 0 {
			jobID = &artifactsAddFlags.job
		}

		// Resolve title: --title takes precedence, then --title-file
		title := artifactsAddFlags.title
		if title == "" && artifactsAddFlags.titleFile != "" {
			data, err := os.ReadFile(artifactsAddFlags.titleFile)
			if err != nil {
				return fmt.Errorf("read title file: %w", err)
			}
			title = strings.TrimSpace(string(data))
		}
		if title == "" {
			return fmt.Errorf("--title or --title-file is required")
		}

		// Resolve options: --options takes precedence, then --options-file
		optionsJSON := artifactsAddFlags.options
		if optionsJSON == "{}" && artifactsAddFlags.optionsFile != "" {
			data, err := os.ReadFile(artifactsAddFlags.optionsFile)
			if err != nil {
				return fmt.Errorf("read options file: %w", err)
			}
			optionsJSON = strings.TrimSpace(string(data))
		}

		// Resolve variants: --variants / --variants-file / --variant-content / --variant-file
		variantsJSON, err := resolveVariants()
		if err != nil {
			return err
		}

		a := db.Artifact{
			SkillID:  artifactsAddFlags.skill,
			JobID:    jobID,
			Title:    title,
			Options:  optionsJSON,
			Variants: variantsJSON,
		}

		created, err := store.AddArtifact(a)
		if err != nil {
			return formatError("failed to add artifact", err)
		}

		if jsonOut {
			printJSON(created)
			return nil
		}

		var variantCount int
		var variants []db.ArtifactVariant
		if err := json.Unmarshal([]byte(created.Variants), &variants); err == nil {
			variantCount = len(variants)
		}

		fmt.Println()
		fmt.Printf("  ✓ Artifact added: %s\n", created.Title)
		fmt.Printf("    ID: %d\n", created.ID)
		fmt.Printf("    Skill: %s\n", created.SkillID)
		fmt.Printf("    Variants: %d\n", variantCount)
		if created.JobID != nil {
			fmt.Printf("    Job ID: %d\n", *created.JobID)
		}
		fmt.Println()
		return nil
	},
}

// resolveVariants builds the variants JSON from the available flags.
// Priority: --variants-file > --variants > --variant-file > --variant-content
func resolveVariants() (string, error) {
	f := artifactsAddFlags

	// 1. --variants-file (JSON array of variants from file)
	if f.variantsFile != "" {
		data, err := os.ReadFile(f.variantsFile)
		if err != nil {
			return "", fmt.Errorf("read variants file: %w", err)
		}
		// Validate it's valid JSON
		var check []db.ArtifactVariant
		if err := json.Unmarshal(data, &check); err != nil {
			return "", fmt.Errorf("invalid variants JSON in %s: %w", f.variantsFile, err)
		}
		return strings.TrimSpace(string(data)), nil
	}

	// 2. --variants (JSON array inline)
	if f.variants != "" {
		var check []db.ArtifactVariant
		if err := json.Unmarshal([]byte(f.variants), &check); err != nil {
			return "", fmt.Errorf("invalid --variants JSON: %w", err)
		}
		return f.variants, nil
	}

	// 3. --variant-file (single variant content from file)
	content := f.variantContent
	if content == "" && f.variantFile != "" {
		data, err := os.ReadFile(f.variantFile)
		if err != nil {
			return "", fmt.Errorf("read variant file: %w", err)
		}
		content = string(data)
	}
	if content == "" {
		return "", fmt.Errorf("provide --variant-content, --variant-file (-f), --variants, or --variants-file")
	}

	label := f.variantLabel
	if label == "" {
		label = "Default"
	}

	v := db.ArtifactVariant{
		Label:   label,
		Content: content,
	}
	data, err := json.Marshal([]db.ArtifactVariant{v})
	if err != nil {
		return "", fmt.Errorf("marshal variant: %w", err)
	}
	return string(data), nil
}

// --- archive ---

var artifactsArchiveCmd = &cobra.Command{
	Use:   "archive <id>",
	Short: "Archive an artifact",
	Long: `Soft-delete an artifact by hiding it from the default list.
Use 'waypoint artifacts list --all' to see archived items.

Examples:
  waypoint artifacts archive 12`,
	Args: cobra.ExactArgs(1),
	RunE: func(cmd *cobra.Command, args []string) error {
		id, err := strconv.ParseInt(args[0], 10, 64)
		if err != nil {
			return fmt.Errorf("invalid artifact ID: %s", args[0])
		}

		if err := store.ArchiveArtifact(id); err != nil {
			return formatError("failed to archive artifact", err)
		}

		if jsonOut {
			printJSON(map[string]any{"archived": true, "id": id})
			return nil
		}

		fmt.Println()
		fmt.Printf("  ✓ Archived artifact %d\n", id)
		fmt.Println()
		return nil
	},
}

func init() {
	rootCmd.AddCommand(artifactsCmd)
	artifactsCmd.AddCommand(artifactsAddCmd)
	artifactsCmd.AddCommand(artifactsListCmd)
	artifactsCmd.AddCommand(artifactsGetCmd)
	artifactsCmd.AddCommand(artifactsDeleteCmd)
	artifactsCmd.AddCommand(artifactsArchiveCmd)

	artifactsAddCmd.Flags().StringVar(&artifactsAddFlags.skill, "skill", "", "Skill ID (email-generator, cover-letter, resume-optimizer, interview-prep, career-summary, statement-of-purpose)")
	artifactsAddCmd.MarkFlagRequired("skill")
	artifactsAddCmd.Flags().Int64Var(&artifactsAddFlags.job, "job", 0, "Link to job ID")
	artifactsAddCmd.Flags().StringVar(&artifactsAddFlags.title, "title", "", "Artifact title")
	artifactsAddCmd.Flags().StringVar(&artifactsAddFlags.titleFile, "title-file", "", "Read artifact title from file")
	artifactsAddCmd.Flags().StringVar(&artifactsAddFlags.variants, "variants", "", "JSON array of variants [{\"label\":\"...\",\"content\":\"...\"}]")
	artifactsAddCmd.Flags().StringVar(&artifactsAddFlags.variantsFile, "variants-file", "", "Read JSON variants array from file")
	artifactsAddCmd.Flags().StringVar(&artifactsAddFlags.variantLabel, "variant-label", "Default", "Label for single-variant artifact")
	artifactsAddCmd.Flags().StringVar(&artifactsAddFlags.variantContent, "variant-content", "", "Inline content for single-variant artifact")
	artifactsAddCmd.Flags().StringVarP(&artifactsAddFlags.variantFile, "variant-file", "f", "", "Read single-variant content from file")
	artifactsAddCmd.Flags().StringVar(&artifactsAddFlags.options, "options", "{}", "JSON object of generation options")
	artifactsAddCmd.Flags().StringVar(&artifactsAddFlags.optionsFile, "options-file", "", "Read JSON options from file")

	artifactsListCmd.Flags().StringVar(&artifactsListFlags.skill, "skill", "", "Filter by skill ID (email-generator, cover-letter, etc.)")
	artifactsListCmd.Flags().Int64Var(&artifactsListFlags.job, "job", 0, "Filter by job ID")
	artifactsListCmd.Flags().BoolVar(&artifactsListFlags.all, "all", false, "Include archived artifacts")

	artifactsDeleteCmd.Flags().BoolVar(&artifactsDeleteFlags.force, "force", false, "Skip confirmation prompt")
}
