package cli

import (
	"encoding/json"
	"fmt"
	"strconv"

	"github.com/SwatiBio/waypoint/internal/db"
	"github.com/spf13/cobra"
)

var artifactsCmd = &cobra.Command{
	Use:     "artifacts",
	Short:   "Manage AI-generated content artifacts",
	Aliases: []string{"artifact"},
	Long: `List, view, and delete content generated by the AI skills
(emails, cover letters, interview prep, resume analysis, career summaries).

Artifacts are created by the skills and stored with all their variants
(e.g. a cover-letter artifact holds the formal, casual, and creative versions).

Examples:
  waypoint artifacts list
  waypoint artifacts list --skill cover-letter --job 5
  waypoint artifacts get 12
  waypoint artifacts delete 12`,
}

// --- list ---

var artifactsListFlags struct {
	skill   string
	job     int64
	all     bool
}

var artifactsListCmd = &cobra.Command{
	Use:   "list",
	Short: "List artifacts",
	Long: `List generated artifacts. By default excludes archived ones.

Filter by skill type (--skill) and/or job (--job).
Use --all to include archived artifacts.

Examples:
  waypoint artifacts list
  waypoint artifacts list --skill cover-letter
  waypoint artifacts list --job 5
  waypoint artifacts list --all`,
	Args: cobra.NoArgs,
	RunE: func(cmd *cobra.Command, args []string) error {
		arts, err := store.GetArtifacts(artifactsListFlags.skill, artifactsListFlags.job, artifactsListFlags.all)
		if err != nil {
			return formatError("failed to list artifacts", err)
		}

		if jsonOut {
			if arts == nil {
				arts = []db.Artifact{}
			}
			printJSON(arts)
			return nil
		}

		fmt.Println()
		if len(arts) == 0 {
			fmt.Println("  No artifacts found.")
			fmt.Println()
			return nil
		}

		rows := make([][]string, 0, len(arts))
		for _, a := range arts {
			var variants []db.ArtifactVariant
			_ = json.Unmarshal(a.Variants, &variants)
			rows = append(rows, []string{
				strconv.FormatInt(a.ID, 10),
				a.SkillID,
				a.Title,
				strconv.Itoa(len(variants)),
				formatDateShort(a.UpdatedAt),
			})
		}

		fmt.Println(formatTable(
			[]string{"ID", "Skill", "Title", "Variants", "Updated"},
			rows,
		))
		fmt.Println()
		return nil
	},
}

// --- get ---

var artifactsGetCmd = &cobra.Command{
	Use:   "get <id>",
	Short: "Show artifact details",
	Long: `Show full details of an artifact including all variants.

Examples:
  waypoint artifacts get 12
  waypoint artifacts get 12 --json`,
	Args: cobra.ExactArgs(1),
	RunE: func(cmd *cobra.Command, args []string) error {
		id, err := strconv.ParseInt(args[0], 10, 64)
		if err != nil {
			return fmt.Errorf("invalid artifact ID: %s", args[0])
		}

		art, err := store.GetArtifact(id)
		if err != nil {
			return err
		}

		if jsonOut {
			printJSON(art)
			return nil
		}

		fmt.Println()
		fmt.Printf("  ID:       %d\n", art.ID)
		fmt.Printf("  Skill:    %s\n", art.SkillID)
		fmt.Printf("  Title:    %s\n", art.Title)
		fmt.Printf("  Archived: %v\n", art.Archived)
		fmt.Printf("  Created:  %s\n", formatDateTime(art.CreatedAt))
		fmt.Printf("  Updated:  %s\n", formatDateTime(art.UpdatedAt))

		var variants []db.ArtifactVariant
		if err := json.Unmarshal(art.Variants, &variants); err != nil {
			return fmt.Errorf("parse variants: %w", err)
		}

		fmt.Println()
		fmt.Printf("  Variants (%d):\n", len(variants))
		for _, v := range variants {
			fmt.Println()
			fmt.Printf("  ── %s ──\n", v.Label)
			fmt.Println(v.Content)
		}
		fmt.Println()
		return nil
	},
}

// --- delete ---

var artifactsDeleteFlags struct {
	force bool
}

var artifactsDeleteCmd = &cobra.Command{
	Use:   "delete <id>",
	Short: "Delete an artifact",
	Long: `Delete an artifact by ID. Prompts for confirmation
unless --force is used.

Examples:
  waypoint artifacts delete 12
  waypoint artifacts delete 12 --force`,
	Args: cobra.ExactArgs(1),
	RunE: func(cmd *cobra.Command, args []string) error {
		id, err := strconv.ParseInt(args[0], 10, 64)
		if err != nil {
			return fmt.Errorf("invalid artifact ID: %s", args[0])
		}

		art, err := store.GetArtifact(id)
		if err != nil {
			return err
		}

		if !artifactsDeleteFlags.force {
			fmt.Printf("  Delete artifact %d (%s)? [y/N]: ", id, art.Title)
			var confirm string
			fmt.Scanln(&confirm)
			if confirm != "y" && confirm != "Y" && confirm != "yes" {
				fmt.Println("  Cancelled.")
				return nil
			}
		}

		if err := store.DeleteArtifact(id); err != nil {
			return formatError("failed to delete artifact", err)
		}

		if jsonOut {
			printJSON(map[string]any{"deleted": true, "id": id, "title": art.Title})
			return nil
		}

		fmt.Println()
		fmt.Printf("  ✓ Deleted artifact %d: %s\n", id, art.Title)
		fmt.Println()
		return nil
	},
}

// --- archive ---

var artifactsArchiveCmd = &cobra.Command{
	Use:   "archive <id>",
	Short: "Archive an artifact",
	Long: `Soft-delete an artifact by hiding it from the default list.
Use 'waypoint artifacts list --all' to see archived items.

Examples:
  waypoint artifacts archive 12`,
	Args: cobra.ExactArgs(1),
	RunE: func(cmd *cobra.Command, args []string) error {
		id, err := strconv.ParseInt(args[0], 10, 64)
		if err != nil {
			return fmt.Errorf("invalid artifact ID: %s", args[0])
		}

		if err := store.ArchiveArtifact(id); err != nil {
			return formatError("failed to archive artifact", err)
		}

		if jsonOut {
			printJSON(map[string]any{"archived": true, "id": id})
			return nil
		}

		fmt.Println()
		fmt.Printf("  ✓ Archived artifact %d\n", id)
		fmt.Println()
		return nil
	},
}

func init() {
	rootCmd.AddCommand(artifactsCmd)
	artifactsCmd.AddCommand(artifactsListCmd)
	artifactsCmd.AddCommand(artifactsGetCmd)
	artifactsCmd.AddCommand(artifactsDeleteCmd)
	artifactsCmd.AddCommand(artifactsArchiveCmd)

	artifactsListCmd.Flags().StringVar(&artifactsListFlags.skill, "skill", "", "Filter by skill ID (email-generator, cover-letter, etc.)")
	artifactsListCmd.Flags().Int64Var(&artifactsListFlags.job, "job", 0, "Filter by job ID")
	artifactsListCmd.Flags().BoolVar(&artifactsListFlags.all, "all", false, "Include archived artifacts")

	artifactsDeleteCmd.Flags().BoolVar(&artifactsDeleteFlags.force, "force", false, "Skip confirmation prompt")
}