package db

import (
	"encoding/json"
	"fmt"
	"time"
)

// Artifact represents content generated by a skill.
// Variants holds multiple outputs from a single generation (e.g. cover letters in different tones).
type Artifact struct {
	ID        int64  `db:"id" json:"id"`
	SkillID   string `db:"skill_id" json:"skillId"`
	JobID     *int64 `db:"job_id" json:"jobId,omitempty"`
	Title     string `db:"title" json:"title"`
	Options   string `db:"options" json:"options"`
	Variants  string `db:"variants" json:"-"` // raw JSON string from DB; emitted as array via MarshalJSON
	Archived  bool   `db:"archived" json:"archived"`
	CreatedAt string `db:"created_at" json:"createdAt"`
	UpdatedAt string `db:"updated_at" json:"updatedAt"`
}

// MarshalJSON ensures Variants is returned as a proper JSON array instead of a string.
func (a Artifact) MarshalJSON() ([]byte, error) {
	type Alias Artifact
	var variants []ArtifactVariant
	if a.Variants != "" {
		if err := json.Unmarshal([]byte(a.Variants), &variants); err != nil {
			variants = []ArtifactVariant{}
		}
	}
	if variants == nil {
		variants = []ArtifactVariant{}
	}
	return json.Marshal(&struct {
		*Alias
		Variants []ArtifactVariant `json:"variants"`
	}{
		Alias:    (*Alias)(&a),
		Variants: variants,
	})
}

// ArtifactVariant is a single output within an artifact generation.
type ArtifactVariant struct {
	Label    string          `json:"label"`
	Content  string          `json:"content"`
	Metadata json.RawMessage `json:"metadata,omitempty"`
}

// GetArtifacts returns artifacts, optionally filtered by skill and/or job.
// By default excludes archived artifacts.
func (s *SQLiteStore) GetArtifacts(skillID string, jobID int64, includeArchived bool) ([]Artifact, error) {
	var (
		conditions []string
		args       []any
	)
	if skillID != "" {
		conditions = append(conditions, "skill_id = ?")
		args = append(args, skillID)
	}
	if jobID > 0 {
		conditions = append(conditions, "job_id = ?")
		args = append(args, jobID)
	}
	if !includeArchived {
		conditions = append(conditions, "archived = 0")
	}

	query := "SELECT id, skill_id, job_id, title, options, variants, archived, created_at, updated_at FROM artifacts"
	if len(conditions) > 0 {
		query += " WHERE " + joinStrings(conditions, " AND ")
	}
	query += " ORDER BY id DESC"

	var arts []Artifact
	if err := s.Select(&arts, query, args...); err != nil {
		return nil, fmt.Errorf("get artifacts: %w", err)
	}
	return arts, nil
}

// GetArtifact returns a single artifact by ID.
func (s *SQLiteStore) GetArtifact(id int64) (Artifact, error) {
	var a Artifact
	err := s.Get(&a, "SELECT id, skill_id, job_id, title, options, variants, archived, created_at, updated_at FROM artifacts WHERE id = ?", id)
	if err != nil {
		return Artifact{}, fmt.Errorf("artifact %d not found", id)
	}
	return a, nil
}

// AddArtifact creates a new artifact.
func (s *SQLiteStore) AddArtifact(a Artifact) (Artifact, error) {
	now := time.Now().UTC().Format(time.RFC3339)
	if a.Options == "" {
		a.Options = "{}"
	}
	if a.Variants == "" {
		a.Variants = "[]"
	}

	result, err := s.Exec(
		`INSERT INTO artifacts (skill_id, job_id, title, options, variants, archived, created_at, updated_at)
		 VALUES (?, ?, ?, ?, ?, 0, ?, ?)`,
		a.SkillID, a.JobID, a.Title, a.Options, a.Variants, now, now,
	)
	if err != nil {
		return Artifact{}, fmt.Errorf("add artifact: %w", err)
	}

	id, _ := result.LastInsertId()
	a.ID = id
	a.CreatedAt = now
	a.UpdatedAt = now
	return a, nil
}

// UpdateArtifact updates an artifact's title, options, or variants.
func (s *SQLiteStore) UpdateArtifact(id int64, updates map[string]any) (Artifact, error) {
	if len(updates) == 0 {
		return s.GetArtifact(id)
	}

	now := time.Now().UTC().Format(time.RFC3339)
	updates["updated_at"] = now

	var (
		setClauses []string
		args       []any
	)
	for key, val := range updates {
		setClauses = append(setClauses, key+" = ?")
		args = append(args, val)
	}
	args = append(args, id)

	query := fmt.Sprintf("UPDATE artifacts SET %s WHERE id = ?", joinStrings(setClauses, ", "))
	if _, err := s.Exec(query, args...); err != nil {
		return Artifact{}, fmt.Errorf("update artifact: %w", err)
	}
	return s.GetArtifact(id)
}

// ArchiveArtifact soft-deletes an artifact.
func (s *SQLiteStore) ArchiveArtifact(id int64) error {
	now := time.Now().UTC().Format(time.RFC3339)
	result, err := s.Exec("UPDATE artifacts SET archived = 1, updated_at = ? WHERE id = ?", now, id)
	if err != nil {
		return fmt.Errorf("archive artifact: %w", err)
	}
	n, _ := result.RowsAffected()
	if n == 0 {
		return fmt.Errorf("artifact %d not found", id)
	}
	return nil
}

// DeleteArtifact permanently removes an artifact.
func (s *SQLiteStore) DeleteArtifact(id int64) error {
	result, err := s.Exec("DELETE FROM artifacts WHERE id = ?", id)
	if err != nil {
		return fmt.Errorf("delete artifact: %w", err)
	}
	n, _ := result.RowsAffected()
	if n == 0 {
		return fmt.Errorf("artifact %d not found", id)
	}
	return nil
}

// joinStrings is a small helper to avoid importing strings in this file.
func joinStrings(parts []string, sep string) string {
	out := ""
	for i, p := range parts {
		if i > 0 {
			out += sep
		}
		out += p
	}
	return out
}

// SearchArtifacts performs full-text search across artifact title and skill_id.
func (s *SQLiteStore) SearchArtifacts(query string) ([]Artifact, error) {
	var arts []Artifact
	err := s.Select(&arts,
		`SELECT a.id, a.skill_id, a.job_id, a.title, a.options, a.variants, a.archived, a.created_at, a.updated_at
		 FROM artifacts a JOIN artifacts_fts f ON a.id = f.rowid
		 WHERE artifacts_fts MATCH ?
		 ORDER BY rank`,
		query,
	)
	if err != nil {
		return nil, fmt.Errorf("search artifacts: %w", err)
	}
	return arts, nil
}

// SearchResultItem is a unified search result from any entity.
type SearchResultItem struct {
	Type  string `json:"type"` // "job" or "artifact"
	ID    int64  `json:"id"`
	Title string `json:"title"`
	Sub   string `json:"sub"`
	Match string `json:"match"` // which field matched
}

// SearchAll performs full-text search across jobs and artifacts, returning unified results.
func (s *SQLiteStore) SearchAll(query string) ([]SearchResultItem, error) {
	var results []SearchResultItem

	// Search jobs. COALESCE(c.name, '') so jobs without a category (NULL
	// from the LEFT JOIN) don't fail the Scan into a Go string — that
	// was silently dropping every uncategorised job from search results.
	jobRows, err := s.Query(
		`SELECT j.id, j.company, j.position, j.status, COALESCE(c.name, '')
		 FROM jobs j
		 LEFT JOIN categories c ON j.category_id = c.id
		 JOIN jobs_fts f ON j.id = f.rowid
		 WHERE jobs_fts MATCH ?
		 ORDER BY rank
		 LIMIT 20`,
		query,
	)
	if err != nil {
		return nil, fmt.Errorf("search jobs: %w", err)
	}
	for jobRows.Next() {
		var id int64
		var company, position, status, catName string
		if err := jobRows.Scan(&id, &company, &position, &status, &catName); err != nil {
			jobRows.Close()
			return nil, fmt.Errorf("scan job row: %w", err)
		}
		results = append(results, SearchResultItem{
			Type:  "job",
			ID:    id,
			Title: company + " — " + position,
			Sub:   status,
			Match: catName,
		})
	}
	jobRows.Close()

	// Search artifacts
	artRows, err := s.Query(
		`SELECT a.id, a.title, a.skill_id
		 FROM artifacts a JOIN artifacts_fts f ON a.id = f.rowid
		 WHERE artifacts_fts MATCH ?
		 ORDER BY rank
		 LIMIT 20`,
		query,
	)
	if err != nil {
		return nil, fmt.Errorf("search artifacts: %w", err)
	}
	for artRows.Next() {
		var id int64
		var title, skillID string
		if err := artRows.Scan(&id, &title, &skillID); err != nil {
			artRows.Close()
			return nil, fmt.Errorf("scan artifact row: %w", err)
		}
		results = append(results, SearchResultItem{
			Type:  "artifact",
			ID:    id,
			Title: title,
			Sub:   skillID,
			Match: "artifact",
		})
	}
	artRows.Close()

	return results, nil
}
