package db

import (
	"encoding/json"
	"fmt"
	"time"
)

// Artifact represents content generated by a skill.
// Variants holds multiple outputs from a single generation (e.g. cover letters in different tones).
type Artifact struct {
	ID        int64           `db:"id" json:"id"`
	SkillID   string          `db:"skill_id" json:"skillId"`
	JobID     *int64          `db:"job_id" json:"jobId,omitempty"`
	Title     string          `db:"title" json:"title"`
	Options   json.RawMessage `db:"options" json:"options"`
	Variants  json.RawMessage `db:"variants" json:"variants"`
	Archived  bool            `db:"archived" json:"archived"`
	CreatedAt string          `db:"created_at" json:"createdAt"`
	UpdatedAt string          `db:"updated_at" json:"updatedAt"`
}

// ArtifactVariant is a single output within an artifact generation.
type ArtifactVariant struct {
	Label    string          `json:"label"`
	Content  string          `json:"content"`
	Metadata json.RawMessage `json:"metadata,omitempty"`
}

// GetArtifacts returns artifacts, optionally filtered by skill and/or job.
// By default excludes archived artifacts.
func (s *Store) GetArtifacts(skillID string, jobID int64, includeArchived bool) ([]Artifact, error) {
	var (
		conditions []string
		args       []any
	)
	if skillID != "" {
		conditions = append(conditions, "skill_id = ?")
		args = append(args, skillID)
	}
	if jobID > 0 {
		conditions = append(conditions, "job_id = ?")
		args = append(args, jobID)
	}
	if !includeArchived {
		conditions = append(conditions, "archived = 0")
	}

	query := "SELECT id, skill_id, job_id, title, options, variants, archived, created_at, updated_at FROM artifacts"
	if len(conditions) > 0 {
		query += " WHERE " + joinStrings(conditions, " AND ")
	}
	query += " ORDER BY id DESC"

	var arts []Artifact
	if err := s.Select(&arts, query, args...); err != nil {
		return nil, fmt.Errorf("get artifacts: %w", err)
	}
	return arts, nil
}

// GetArtifact returns a single artifact by ID.
func (s *Store) GetArtifact(id int64) (Artifact, error) {
	var a Artifact
	err := s.Get(&a, "SELECT id, skill_id, job_id, title, options, variants, archived, created_at, updated_at FROM artifacts WHERE id = ?", id)
	if err != nil {
		return Artifact{}, fmt.Errorf("artifact %d not found", id)
	}
	return a, nil
}

// AddArtifact creates a new artifact.
func (s *Store) AddArtifact(a Artifact) (Artifact, error) {
	now := time.Now().UTC().Format(time.RFC3339)
	if a.Options == nil {
		a.Options = json.RawMessage("{}")
	}
	if a.Variants == nil {
		a.Variants = json.RawMessage("[]")
	}

	result, err := s.Exec(
		`INSERT INTO artifacts (skill_id, job_id, title, options, variants, archived, created_at, updated_at)
		 VALUES (?, ?, ?, ?, ?, 0, ?, ?)`,
		a.SkillID, a.JobID, a.Title, []byte(a.Options), []byte(a.Variants), now, now,
	)
	if err != nil {
		return Artifact{}, fmt.Errorf("add artifact: %w", err)
	}

	id, _ := result.LastInsertId()
	a.ID = id
	a.CreatedAt = now
	a.UpdatedAt = now
	return a, nil
}

// UpdateArtifact updates an artifact's title, options, or variants.
func (s *Store) UpdateArtifact(id int64, updates map[string]any) (Artifact, error) {
	if len(updates) == 0 {
		return s.GetArtifact(id)
	}

	now := time.Now().UTC().Format(time.RFC3339)
	updates["updated_at"] = now

	var (
		setClauses []string
		args       []any
	)
	for key, val := range updates {
		setClauses = append(setClauses, key+" = ?")
		args = append(args, val)
	}
	args = append(args, id)

	query := fmt.Sprintf("UPDATE artifacts SET %s WHERE id = ?", joinStrings(setClauses, ", "))
	if _, err := s.Exec(query, args...); err != nil {
		return Artifact{}, fmt.Errorf("update artifact: %w", err)
	}
	return s.GetArtifact(id)
}

// ArchiveArtifact soft-deletes an artifact.
func (s *Store) ArchiveArtifact(id int64) error {
	now := time.Now().UTC().Format(time.RFC3339)
	result, err := s.Exec("UPDATE artifacts SET archived = 1, updated_at = ? WHERE id = ?", now, id)
	if err != nil {
		return fmt.Errorf("archive artifact: %w", err)
	}
	n, _ := result.RowsAffected()
	if n == 0 {
		return fmt.Errorf("artifact %d not found", id)
	}
	return nil
}

// DeleteArtifact permanently removes an artifact.
func (s *Store) DeleteArtifact(id int64) error {
	result, err := s.Exec("DELETE FROM artifacts WHERE id = ?", id)
	if err != nil {
		return fmt.Errorf("delete artifact: %w", err)
	}
	n, _ := result.RowsAffected()
	if n == 0 {
		return fmt.Errorf("artifact %d not found", id)
	}
	return nil
}

// joinStrings is a small helper to avoid importing strings in this file.
func joinStrings(parts []string, sep string) string {
	out := ""
	for i, p := range parts {
		if i > 0 {
			out += sep
		}
		out += p
	}
	return out
}
